# Generated by Django 5.2.1 on 2025-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrockMaster', '0005_alter_activitylog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
