# Generated by Django 5.2.1 on 2025-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SrockMaster', '0006_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
